package cl.fapp;

import cl.fapp.sii.signer.common.XmlSigner;

public class PruebaFirmas {

	public static void main(String[] args) {
		@SuppressWarnings("unused")
		String encabezadoBoleta = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"no\"?><BOLETADefType xmlns:ns2=\"http://www.w3.org/2000/09/xmldsig#\" version=\"1.0\">\r\n";
		String xmlcontentDTE = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"no\"?>" + "<DTE version=\"1.0\">\r\n"
				+ "<Documento ID=\"B000000000120220713121035\">\r\n"
				+ "<Encabezado>\r\n"
				+ "<IdDoc>\r\n"
				+ "<TipoDTE>39</TipoDTE>\r\n"
				+ "<Folio>1</Folio>\r\n"
				+ "<FchEmis>2022-07-13</FchEmis>\r\n"
				+ "<IndServicio>3</IndServicio>\r\n"
				+ "<IndMntNeto>1</IndMntNeto>\r\n"
				+ "</IdDoc>\r\n"
				+ "<Emisor>\r\n"
				+ "<RUTEmisor>76447325-6</RUTEmisor>\r\n"
				+ "<RznSocEmisor>INVERSIONES RECABARREN CLARO SPA</RznSocEmisor>\r\n"
				+ "<GiroEmisor>INMOBILIARIA</GiroEmisor>\r\n"
				+ "</Emisor>\r\n"
				+ "<Receptor>\r\n"
				+ "<RUTRecep>66666666-6</RUTRecep>\r\n"
				+ "</Receptor>\r\n"
				+ "<Totales>\r\n"
				+ "<MntNeto>8</MntNeto>\r\n"
				+ "<MntExe>0</MntExe>\r\n"
				+ "<IVA>1</IVA>\r\n"
				+ "<MntTotal>9</MntTotal>\r\n"
				+ "<MontoNF>0</MontoNF>\r\n"
				+ "<TotalPeriodo>0</TotalPeriodo>\r\n"
				+ "<SaldoAnterior>0</SaldoAnterior>\r\n"
				+ "<VlrPagar>0</VlrPagar>\r\n"
				+ "</Totales>\r\n"
				+ "</Encabezado>\r\n"
				+ "<Detalle>\r\n"
				+ "<NroLinDet>1</NroLinDet>\r\n"
				+ "<IndExe>0</IndExe>\r\n"
				+ "<RUTMandante>rutmandante</RUTMandante>\r\n"
				+ "<NmbItem>Nombre del producto</NmbItem>\r\n"
				+ "<DscItem>item1</DscItem>\r\n"
				+ "<QtyItem>1</QtyItem>\r\n"
				+ "<UnmdItem>kg</UnmdItem>\r\n"
				+ "<PrcItem>10</PrcItem>\r\n"
				+ "<DescuentoPct>0</DescuentoPct>\r\n"
				+ "<DescuentoMonto>0</DescuentoMonto>\r\n"
				+ "<RecargoPct>0</RecargoPct>\r\n"
				+ "<RecargoMonto>10</RecargoMonto>\r\n"
				+ "<MontoItem>10</MontoItem>\r\n"
				+ "</Detalle>\r\n"
				+ "<Referencia>\r\n"
				+ "<NroLinRef>1</NroLinRef>\r\n"
				+ "<CodRef>SET</CodRef>\r\n"
				+ "<RazonRef>CASO-1</RazonRef>\r\n"
				+ "<CodVndor>V001</CodVndor>\r\n"
				+ "<CodCaja>C001</CodCaja>\r\n"
				+ "</Referencia>\r\n"
				+ "<TED version=\"1.0\">\r\n"
				+ "<DD>\r\n"
				+ "<RE>76447325-6</RE>\r\n"
				+ "<TD>39</TD>\r\n"
				+ "<F>1</F>\r\n"
				+ "<FE>2022-07-13</FE>\r\n"
				+ "<RR>66666666-6</RR>\r\n"
				+ "<MNT>9</MNT>\r\n"
				+ "<IT1>item1</IT1>\r\n"
				+ "<CAF version=\"1.0\">\r\n"
				+ "<DA>\r\n"
				+ "<RE>76447325-6</RE>\r\n"
				+ "<RS>INVERSIONES RECABARREN CLARO SPA</RS>\r\n"
				+ "<TD>39</TD>\r\n"
				+ "<RNG>\r\n"
				+ "<D>1</D>\r\n"
				+ "<H>5</H>\r\n"
				+ "</RNG>\r\n"
				+ "<FA>2022-05-16</FA>\r\n"
				+ "<RSAPK>\r\n"
				+ "<M>2TkioiaNFL1dIYnHJH9bsgb+6uH0zj2jTVKBzcVt1zqVE4BlxzSP6Sr5svFV2axubZu8MAHwqeczLoF+EmqGGQ==</M>\r\n"
				+ "<E>Aw==</E>\r\n"
				+ "</RSAPK>\r\n"
				+ "<IDK>100</IDK>\r\n"
				+ "</DA>\r\n"
				+ "<FRMA algoritmo=\"SHA1withRSA\">uh5f61ql47lcwGLVly6eefviM5VLk1dyz7LGdZOxNSnVXHkAxX3e5wkJ6BRU66NWFZZxA+jKmu8/PqEPzWCa9g==</FRMA>\r\n"
				+ "</CAF>\r\n"
				+ "<TSTED>2022-07-13T12:10:35</TSTED>\r\n"
				+ "</DD>\r\n"
				+ "<FRMT algoritmo=\"SHA1withRSA\">c2hEKzY4WFMrSFVTdzBDMFBNN2xWT0dKTFNOOThIMVhxL3JGM2JVenlRSGF5M1FxQ3pHcDhCMTdoaXBucWFHMHNlK1FUbW51UUNhMFlPQVpub3UxRUE9PQ==</FRMT>\r\n"
				+ "</TED>\r\n"
				+ "<TmstFirma>2022-07-13T12:10:35</TmstFirma>\r\n"
				+ "</Documento>\r\n"
				+ "<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\">\r\n"
				+ "<SignedInfo>\r\n"
				+ "<CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/>\r\n"
				+ "<SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/>\r\n"
				+ "<Reference URI=\"#B000000000120220713121035\">\r\n"
				+ "<Transforms>\r\n"
				+ "<Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/>\r\n"
				+ "</Transforms>\r\n"
				+ "<DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>\r\n"
				+ "<DigestValue>0Vlkysn5i26cPlzSC4hkjPEiCgc=</DigestValue>\r\n"
				+ "</Reference>\r\n"
				+ "</SignedInfo>\r\n"
				+ "<SignatureValue>HPHwFKh06ztaSVk2QijGmMZUhDQ5kN11xS/sYBRW8KmPT8rukb5jMcQpKEFYzMXnb3/xfeYubBjL&#13;\r\n"
				+ "NWkAfcMDiaGIX0qZQNbKT6kkjQVu2qH2T8vu3zlBjNy+FzpMF42B+YJHJg/20WgGQZ++JABmakGP&#13;\r\n"
				+ "ueG7rOwQj3t2RtCHQbj0WvG+GEoEnIBHAndNwfKXmizSWdPfSFwtHmVtDabsicgp/58VErRawrXi&#13;\r\n"
				+ "LE6pgq9VpUMGX0EOuSkfgUgd7IMHt7yW3zLte1JCrFY6//Svo4VVPYXI8IwSEHePLU6X1eYho9tk&#13;\r\n"
				+ "LxrXVE4CfXyHB0CMPssCpBi7GJrD6id2TJ9jRA==</SignatureValue>\r\n"
				+ "<KeyInfo>\r\n"
				+ "<KeyValue>\r\n"
				+ "<RSAKeyValue>\r\n"
				+ "<Modulus>ySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLkadQb8xX15&#13;\r\n"
				+ "Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRturqgW2zc4x&#13;\r\n"
				+ "J02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7mkUVKUyf/&#13;\r\n"
				+ "dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SHcp/344bG&#13;\r\n"
				+ "hJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSw==</Modulus>\r\n"
				+ "<Exponent>AQAB</Exponent>\r\n"
				+ "</RSAKeyValue>\r\n"
				+ "</KeyValue>\r\n"
				+ "<X509Data>\r\n"
				+ "<X509Certificate>MIIH3TCCBcWgAwIBAgIKESP5LQABAAFMAjANBgkqhkiG9w0BAQsFADCBvzELMAkGA1UEBhMCQ0wx&#13;\r\n"
				+ "HTAbBgNVBAgTFFJlZ2lvbiBNZXRyb3BvbGl0YW5hMREwDwYDVQQHEwhTYW50aWFnbzEUMBIGA1UE&#13;\r\n"
				+ "ChMLRS1DRVJUQ0hJTEUxIDAeBgNVBAsTF0F1dG9yaWRhZCBDZXJ0aWZpY2Fkb3JhMR4wHAYDVQQD&#13;\r\n"
				+ "ExVFLUNFUlRDSElMRSBDQSBGRVMgMDIxJjAkBgkqhkiG9w0BCQEWF3NjbGllbnRlQGUtY2VydGNo&#13;\r\n"
				+ "aWxlLmNsMB4XDTIyMDUxMjE5MzUyMloXDTIzMDUxMjE5MzUyMlowgdkxCzAJBgNVBAYTAkNMMSIw&#13;\r\n"
				+ "IAYDVQQIExlNRVRST1BPTElUQU5BIERFIFNBTlRJQUdPMREwDwYDVQQHEwhTQU5USUFHTzE8MDoG&#13;\r\n"
				+ "A1UEChMzU0lTVEVNQVMgVEVDTk9MT0dJQ09TIElORk9STUFUSUNPUyBUUkFOU0ZPUk1BUFAgU1BB&#13;\r\n"
				+ "MQowCAYDVQQLDAEqMSEwHwYDVQQDExhDTEFVRElPIENPUlJFQSBCRVRBTkNPVVIxJjAkBgkqhkiG&#13;\r\n"
				+ "9w0BCQEWF0NDT1JSRUFAVFJBTlNGT1JNQVBQLkNMMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB&#13;\r\n"
				+ "CgKCAQEAySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLka&#13;\r\n"
				+ "dQb8xX15Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRtur&#13;\r\n"
				+ "qgW2zc4xJ02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7m&#13;\r\n"
				+ "kUVKUyf/dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SH&#13;\r\n"
				+ "cp/344bGhJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSwIDAQABo4ICvTCCArkwggFfBgNVHSAE&#13;\r\n"
				+ "ggFWMIIBUjCCAU4GCCsGAQQBw1IFMIIBQDA9BggrBgEFBQcCARYxaHR0cHM6Ly93d3cuZS1jZXJ0&#13;\r\n"
				+ "Y2hpbGUuY2wvcG9saXRpY2FzLXktcHJhY3RpY2FzLzCB/gYIKwYBBQUHAgIwgfEege4ARQBsACAA&#13;\r\n"
				+ "cgBlAHMAcABvAG4AZABlAHIAIABlAHMAdABlACAAZgBvAHIAbQB1AGwAYQByAGkAbwAgAGUAcwAg&#13;\r\n"
				+ "AHUAbgAgAHIAZQBxAHUAaQBzAGkAdABvACAAaQBuAGQAaQBzAHAAZQBuAHMAYQBiAGwAZQAgAHAA&#13;\r\n"
				+ "YQByAGEAIABkAGEAcgAgAGkAbgBpAGMAaQBvACAAYQBsACAAcAByAG8AYwBlAHMAbwAgAGQAZQAg&#13;\r\n"
				+ "AGMAZQByAHQAaQBmAGkAYwBhAGMAaQDzAG4ALgAgAFAAbwBzAHQAZQByAGkAbwByAG0AZQBuAHQA&#13;\r\n"
				+ "ZQAsMB0GA1UdDgQWBBSAYI7nYNtsjzfZ5hi49+IB28bYzTALBgNVHQ8EBAMCBPAwIwYDVR0RBBww&#13;\r\n"
				+ "GqAYBggrBgEEAcEBAaAMFgoxNDMzNjk2MC05MB8GA1UdIwQYMBaAFHTWIbP0WugtfLtZBmND72m0&#13;\r\n"
				+ "OpMEMEAGA1UdHwQ5MDcwNaAzoDGGL2h0dHA6Ly9jcmwuZWNlcnRjaGlsZS5jbC9FLUNFUlRDSElM&#13;\r\n"
				+ "RUNBRkVTMDIuY3JsMD0GCCsGAQUFBwEBBDEwLzAtBggrBgEFBQcwAYYhaHR0cDovL29jc3BmZXMu&#13;\r\n"
				+ "ZWNlcnRjaGlsZS5jbC9vY3NwMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIHd0k2X1DqGiZ0G&#13;\r\n"
				+ "h4jOb4OvzGBFhaS+OIKen20CAWQCAQIwIwYDVR0SBBwwGqAYBggrBgEEAcEBAqAMFgo5NjkyODE4&#13;\r\n"
				+ "MC01MA0GCSqGSIb3DQEBCwUAA4ICAQA1N0v7yylmdqxUQK6SYJ3KUrP+0p5vq2iOkoQDa4cf6i8/&#13;\r\n"
				+ "RI1x31XoyuVSCT9G5GTI9O/N6sf6a2ClFdvpHsDP+vPEkVmoHB9Uiie4zxptC7xuWC1Gs2HIkSbQ&#13;\r\n"
				+ "ERr5oHVYGDjXn/n5HdwNoDkTxzXmE2Xd5sr+fk4stHckHileCUYSYuCUOPHXjMa6WArFZ/dUYqgs&#13;\r\n"
				+ "pWVSbZzOrGxTkTfCXasacl7xrCxoF//zF+twiv6WLItV4mR7hULUMEU7dk7xEAn8xtQtYqkb8PMr&#13;\r\n"
				+ "RfzeQZT3Zc8J2wENi+GA5PtDtGJbq6BYNQpIB4Oqql+n3sCdFYPO3L+0uSIRaMCB+T8jgCeKDzEv&#13;\r\n"
				+ "+FOTxIs02BsYDBxjkjk1r4h71ZKKxHUSiX+qsJYiYWZF4NYpucPAUCxpUcZUhfYjxfzRoxl70ubB&#13;\r\n"
				+ "ATn6apsuAh/gOjTkod54k99frNdJoS0HSoQHua/JEKxbGQCY3tNMMcWHGOA1gI8OLI6dEwfdHNdN&#13;\r\n"
				+ "5PSCQnAvsnQ9kdcj2fLc070cxWy32Nr4aMQZqNONGZEQnz3CBWJwEaMDqJHd/7Ka7RLM4RjFqP76&#13;\r\n"
				+ "MMJIRwK+4iXHtjr54k5i8m4oLPO1ZuOuZN+VDB7+xx3eshLbRQS2kJxaeYCX8sG7WKcvl1Nc10gZ&#13;\r\n"
				+ "SC1xp6jBYer6VC7Q7tc3qfDUhHC7pg==</X509Certificate>\r\n"
				+ "</X509Data>\r\n"
				+ "</KeyInfo>\r\n"
				+ "</Signature>\r\n"
				+ "</DTE>";
				
		
		String xmlcontentSetDTE = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"no\"?><EnvioBOLETA xmlns:ns2=\"http://www.w3.org/2000/09/xmldsig#\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"1.0\" xsi:schemaLocation=\"http://www.sii.cl/SiiDte EnvioBOLETA_v11.xsd\">\r\n"
				+ "<SetDTE ID=\"S20220715003300\">\r\n"
				+ "<Caratula version=\"1.0\">\r\n"
				+ "<RutEmisor>76447325-6</RutEmisor>\r\n"
				+ "<RutEnvia>76447325-6</RutEnvia>\r\n"
				+ "<RutReceptor>76447325-6</RutReceptor>\r\n"
				+ "<TmstFirmaEnv>2022-07-15T12:33:00</TmstFirmaEnv>\r\n"
				+ "<SubTotDTE>\r\n"
				+ "<TpoDTE>39</TpoDTE>\r\n"
				+ "<NroDTE>2</NroDTE>\r\n"
				+ "</SubTotDTE>\r\n"
				+ "</Caratula>\r\n"
				+ "<DTE version=\"1.0\">\r\n"
				+ "<Documento ID=\"B202207150032520000000002\">\r\n"
				+ "<Encabezado>\r\n"
				+ "<IdDoc>\r\n"
				+ "<TipoDTE>39</TipoDTE>\r\n"
				+ "<Folio>2</Folio>\r\n"
				+ "<FchEmis>2022-07-15</FchEmis>\r\n"
				+ "<IndServicio>3</IndServicio>\r\n"
				+ "<IndMntNeto>1</IndMntNeto>\r\n"
				+ "</IdDoc>\r\n"
				+ "<Emisor>\r\n"
				+ "<RUTEmisor>76447325-6</RUTEmisor>\r\n"
				+ "<RznSocEmisor>INVERSIONES RECABARREN CLARO SPA</RznSocEmisor>\r\n"
				+ "<GiroEmisor>INMOBILIARIA</GiroEmisor>\r\n"
				+ "</Emisor>\r\n"
				+ "<Receptor>\r\n"
				+ "<RUTRecep>66666666-6</RUTRecep>\r\n"
				+ "</Receptor>\r\n"
				+ "<Totales>\r\n"
				+ "<MntNeto>25042</MntNeto>\r\n"
				+ "<MntExe>29800</MntExe>\r\n"
				+ "<IVA>4757</IVA>\r\n"
				+ "<MntTotal>59599</MntTotal>\r\n"
				+ "</Totales>\r\n"
				+ "</Encabezado>\r\n"
				+ "<Detalle>\r\n"
				+ "<NroLinDet>1</NroLinDet>\r\n"
				+ "<IndExe>1</IndExe>\r\n"
				+ "<NmbItem>Cambio de aceite</NmbItem>\r\n"
				+ "<QtyItem>1</QtyItem>\r\n"
				+ "<PrcItem>19900</PrcItem>\r\n"
				+ "<RecargoMonto>19900</RecargoMonto>\r\n"
				+ "<MontoItem>19900</MontoItem>\r\n"
				+ "</Detalle>\r\n"
				+ "<Detalle>\r\n"
				+ "<NroLinDet>2</NroLinDet>\r\n"
				+ "<IndExe>1</IndExe>\r\n"
				+ "<NmbItem>Alineacion y balanceo</NmbItem>\r\n"
				+ "<QtyItem>1</QtyItem>\r\n"
				+ "<PrcItem>9900</PrcItem>\r\n"
				+ "<RecargoMonto>9900</RecargoMonto>\r\n"
				+ "<MontoItem>9900</MontoItem>\r\n"
				+ "</Detalle>\r\n"
				+ "<Referencia>\r\n"
				+ "<NroLinRef>1</NroLinRef>\r\n"
				+ "<CodRef>SET</CodRef>\r\n"
				+ "<RazonRef>CASO-1</RazonRef>\r\n"
				+ "</Referencia>\r\n"
				+ "<TED version=\"1.0\">\r\n"
				+ "<DD>\r\n"
				+ "<RE>76447325-6</RE>\r\n"
				+ "<TD>39</TD>\r\n"
				+ "<F>2</F>\r\n"
				+ "<FE>2022-07-15</FE>\r\n"
				+ "<RR>66666666-6</RR>\r\n"
				+ "<MNT>59599</MNT>\r\n"
				+ "<CAF version=\"1.0\">\r\n"
				+ "<DA>\r\n"
				+ "<RE>76447325-6</RE>\r\n"
				+ "<RS>INVERSIONES RECABARREN CLARO SPA</RS>\r\n"
				+ "<TD>39</TD>\r\n"
				+ "<RNG>\r\n"
				+ "<D>1</D>\r\n"
				+ "<H>5</H>\r\n"
				+ "</RNG>\r\n"
				+ "<FA>2022-05-16</FA>\r\n"
				+ "<RSAPK>\r\n"
				+ "<M>2TkioiaNFL1dIYnHJH9bsgb+6uH0zj2jTVKBzcVt1zqVE4BlxzSP6Sr5svFV2axubZu8MAHwqeczLoF+EmqGGQ==</M>\r\n"
				+ "<E>Aw==</E>\r\n"
				+ "</RSAPK>\r\n"
				+ "<IDK>100</IDK>\r\n"
				+ "</DA>\r\n"
				+ "<FRMA algoritmo=\"SHA1withRSA\">uh5f61ql47lcwGLVly6eefviM5VLk1dyz7LGdZOxNSnVXHkAxX3e5wkJ6BRU66NWFZZxA+jKmu8/PqEPzWCa9g==</FRMA>\r\n"
				+ "</CAF>\r\n"
				+ "<TSTED>2022-07-15T12:32:52</TSTED>\r\n"
				+ "</DD>\r\n"
				+ "<FRMT algoritmo=\"SHA1withRSA\">YU9NNXVkNnNiSm0vS0NOTGZlWTJ4UUt4eXdRQWxETTR2ZGYrc0l6Qy9XeVRDbGJqQ1N6R1VUQ2RUVnJxMEp0UVl3RW42Y1ZPT0cyTnBwNVJCVTBTRlE9PQ==</FRMT>\r\n"
				+ "</TED>\r\n"
				+ "<TmstFirma>2022-07-15T12:32:52</TmstFirma>\r\n"
				+ "</Documento>\r\n"
				+ "<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"><SignedInfo><CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/><SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/><Reference URI=\"#B202207150032520000000002\"><Transforms><Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/></Transforms><DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><DigestValue>hHerDQymS0bTIHMaNVM4QBp+Als=</DigestValue></Reference></SignedInfo><SignatureValue>wonRJy8uWI18n7Wxp1hRIOg/BDlNc96aYs5oR4W260t3iz/vxWOxTrKwnSiuBbf7ysph+7zaywYH/9klkZnvA0+ZfGmtB8amaJ8wIpCRSSzTAKrkJOEdqK7QO2xnb99eexhCKjgz9KRvUv+MH1N8wO8ADH7/unva/iyuGCfKroVsWfG6j+FjwkRlaBSZl8TaTum+XTthSNcyGyDonGMGdobCXcKQklQUaxNCtssdUGU4fAXtjFum89E+n8JFDS+o/ee8dz068ii9vaDakr7TZaJWpfsSN/WH7KoTkLQJGKZ9k3ay9bSm/bpw760lWbn75hj0zO2G7E6ATeFyKsOs+A==</SignatureValue><KeyInfo><KeyValue><RSAKeyValue><Modulus>ySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLkadQb8xX15Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRturqgW2zc4xJ02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7mkUVKUyf/dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SHcp/344bGhJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSw==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue><X509Data><X509Certificate>MIIH3TCCBcWgAwIBAgIKESP5LQABAAFMAjANBgkqhkiG9w0BAQsFADCBvzELMAkGA1UEBhMCQ0wxHTAbBgNVBAgTFFJlZ2lvbiBNZXRyb3BvbGl0YW5hMREwDwYDVQQHEwhTYW50aWFnbzEUMBIGA1UEChMLRS1DRVJUQ0hJTEUxIDAeBgNVBAsTF0F1dG9yaWRhZCBDZXJ0aWZpY2Fkb3JhMR4wHAYDVQQDExVFLUNFUlRDSElMRSBDQSBGRVMgMDIxJjAkBgkqhkiG9w0BCQEWF3NjbGllbnRlQGUtY2VydGNoaWxlLmNsMB4XDTIyMDUxMjE5MzUyMloXDTIzMDUxMjE5MzUyMlowgdkxCzAJBgNVBAYTAkNMMSIwIAYDVQQIExlNRVRST1BPTElUQU5BIERFIFNBTlRJQUdPMREwDwYDVQQHEwhTQU5USUFHTzE8MDoGA1UEChMzU0lTVEVNQVMgVEVDTk9MT0dJQ09TIElORk9STUFUSUNPUyBUUkFOU0ZPUk1BUFAgU1BBMQowCAYDVQQLDAEqMSEwHwYDVQQDExhDTEFVRElPIENPUlJFQSBCRVRBTkNPVVIxJjAkBgkqhkiG9w0BCQEWF0NDT1JSRUFAVFJBTlNGT1JNQVBQLkNMMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLkadQb8xX15Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRturqgW2zc4xJ02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7mkUVKUyf/dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SHcp/344bGhJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSwIDAQABo4ICvTCCArkwggFfBgNVHSAEggFWMIIBUjCCAU4GCCsGAQQBw1IFMIIBQDA9BggrBgEFBQcCARYxaHR0cHM6Ly93d3cuZS1jZXJ0Y2hpbGUuY2wvcG9saXRpY2FzLXktcHJhY3RpY2FzLzCB/gYIKwYBBQUHAgIwgfEege4ARQBsACAAcgBlAHMAcABvAG4AZABlAHIAIABlAHMAdABlACAAZgBvAHIAbQB1AGwAYQByAGkAbwAgAGUAcwAgAHUAbgAgAHIAZQBxAHUAaQBzAGkAdABvACAAaQBuAGQAaQBzAHAAZQBuAHMAYQBiAGwAZQAgAHAAYQByAGEAIABkAGEAcgAgAGkAbgBpAGMAaQBvACAAYQBsACAAcAByAG8AYwBlAHMAbwAgAGQAZQAgAGMAZQByAHQAaQBmAGkAYwBhAGMAaQDzAG4ALgAgAFAAbwBzAHQAZQByAGkAbwByAG0AZQBuAHQAZQAsMB0GA1UdDgQWBBSAYI7nYNtsjzfZ5hi49+IB28bYzTALBgNVHQ8EBAMCBPAwIwYDVR0RBBwwGqAYBggrBgEEAcEBAaAMFgoxNDMzNjk2MC05MB8GA1UdIwQYMBaAFHTWIbP0WugtfLtZBmND72m0OpMEMEAGA1UdHwQ5MDcwNaAzoDGGL2h0dHA6Ly9jcmwuZWNlcnRjaGlsZS5jbC9FLUNFUlRDSElMRUNBRkVTMDIuY3JsMD0GCCsGAQUFBwEBBDEwLzAtBggrBgEFBQcwAYYhaHR0cDovL29jc3BmZXMuZWNlcnRjaGlsZS5jbC9vY3NwMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIHd0k2X1DqGiZ0Gh4jOb4OvzGBFhaS+OIKen20CAWQCAQIwIwYDVR0SBBwwGqAYBggrBgEEAcEBAqAMFgo5NjkyODE4MC01MA0GCSqGSIb3DQEBCwUAA4ICAQA1N0v7yylmdqxUQK6SYJ3KUrP+0p5vq2iOkoQDa4cf6i8/RI1x31XoyuVSCT9G5GTI9O/N6sf6a2ClFdvpHsDP+vPEkVmoHB9Uiie4zxptC7xuWC1Gs2HIkSbQERr5oHVYGDjXn/n5HdwNoDkTxzXmE2Xd5sr+fk4stHckHileCUYSYuCUOPHXjMa6WArFZ/dUYqgspWVSbZzOrGxTkTfCXasacl7xrCxoF//zF+twiv6WLItV4mR7hULUMEU7dk7xEAn8xtQtYqkb8PMrRfzeQZT3Zc8J2wENi+GA5PtDtGJbq6BYNQpIB4Oqql+n3sCdFYPO3L+0uSIRaMCB+T8jgCeKDzEv+FOTxIs02BsYDBxjkjk1r4h71ZKKxHUSiX+qsJYiYWZF4NYpucPAUCxpUcZUhfYjxfzRoxl70ubBATn6apsuAh/gOjTkod54k99frNdJoS0HSoQHua/JEKxbGQCY3tNMMcWHGOA1gI8OLI6dEwfdHNdN5PSCQnAvsnQ9kdcj2fLc070cxWy32Nr4aMQZqNONGZEQnz3CBWJwEaMDqJHd/7Ka7RLM4RjFqP76MMJIRwK+4iXHtjr54k5i8m4oLPO1ZuOuZN+VDB7+xx3eshLbRQS2kJxaeYCX8sG7WKcvl1Nc10gZSC1xp6jBYer6VC7Q7tc3qfDUhHC7pg==</X509Certificate></X509Data></KeyInfo></Signature></DTE>\r\n"
				+ "<DTE version=\"1.0\">\r\n"
				+ "<Documento ID=\"B202207150032560000000003\">\r\n"
				+ "<Encabezado>\r\n"
				+ "<IdDoc>\r\n"
				+ "<TipoDTE>39</TipoDTE>\r\n"
				+ "<Folio>3</Folio>\r\n"
				+ "<FchEmis>2022-07-15</FchEmis>\r\n"
				+ "<IndServicio>3</IndServicio>\r\n"
				+ "<IndMntNeto>1</IndMntNeto>\r\n"
				+ "</IdDoc>\r\n"
				+ "<Emisor>\r\n"
				+ "<RUTEmisor>76447325-6</RUTEmisor>\r\n"
				+ "<RznSocEmisor>INVERSIONES RECABARREN CLARO SPA</RznSocEmisor>\r\n"
				+ "<GiroEmisor>INMOBILIARIA</GiroEmisor>\r\n"
				+ "</Emisor>\r\n"
				+ "<Receptor>\r\n"
				+ "<RUTRecep>66666666-6</RUTRecep>\r\n"
				+ "</Receptor>\r\n"
				+ "<Totales>\r\n"
				+ "<MntNeto>25042</MntNeto>\r\n"
				+ "<MntExe>29800</MntExe>\r\n"
				+ "<IVA>4757</IVA>\r\n"
				+ "<MntTotal>59599</MntTotal>\r\n"
				+ "</Totales>\r\n"
				+ "</Encabezado>\r\n"
				+ "<Detalle>\r\n"
				+ "<NroLinDet>1</NroLinDet>\r\n"
				+ "<IndExe>1</IndExe>\r\n"
				+ "<NmbItem>Cambio de aceite</NmbItem>\r\n"
				+ "<QtyItem>1</QtyItem>\r\n"
				+ "<PrcItem>19900</PrcItem>\r\n"
				+ "<RecargoMonto>19900</RecargoMonto>\r\n"
				+ "<MontoItem>19900</MontoItem>\r\n"
				+ "</Detalle>\r\n"
				+ "<Detalle>\r\n"
				+ "<NroLinDet>2</NroLinDet>\r\n"
				+ "<IndExe>1</IndExe>\r\n"
				+ "<NmbItem>Alineacion y balanceo</NmbItem>\r\n"
				+ "<QtyItem>1</QtyItem>\r\n"
				+ "<PrcItem>9900</PrcItem>\r\n"
				+ "<RecargoMonto>9900</RecargoMonto>\r\n"
				+ "<MontoItem>9900</MontoItem>\r\n"
				+ "</Detalle>\r\n"
				+ "<Referencia>\r\n"
				+ "<NroLinRef>1</NroLinRef>\r\n"
				+ "<CodRef>SET</CodRef>\r\n"
				+ "<RazonRef>CASO-1</RazonRef>\r\n"
				+ "</Referencia>\r\n"
				+ "<TED version=\"1.0\">\r\n"
				+ "<DD>\r\n"
				+ "<RE>76447325-6</RE>\r\n"
				+ "<TD>39</TD>\r\n"
				+ "<F>3</F>\r\n"
				+ "<FE>2022-07-15</FE>\r\n"
				+ "<RR>66666666-6</RR>\r\n"
				+ "<MNT>59599</MNT>\r\n"
				+ "<CAF version=\"1.0\">\r\n"
				+ "<DA>\r\n"
				+ "<RE>76447325-6</RE>\r\n"
				+ "<RS>INVERSIONES RECABARREN CLARO SPA</RS>\r\n"
				+ "<TD>39</TD>\r\n"
				+ "<RNG>\r\n"
				+ "<D>1</D>\r\n"
				+ "<H>5</H>\r\n"
				+ "</RNG>\r\n"
				+ "<FA>2022-05-16</FA>\r\n"
				+ "<RSAPK>\r\n"
				+ "<M>2TkioiaNFL1dIYnHJH9bsgb+6uH0zj2jTVKBzcVt1zqVE4BlxzSP6Sr5svFV2axubZu8MAHwqeczLoF+EmqGGQ==</M>\r\n"
				+ "<E>Aw==</E>\r\n"
				+ "</RSAPK>\r\n"
				+ "<IDK>100</IDK>\r\n"
				+ "</DA>\r\n"
				+ "<FRMA algoritmo=\"SHA1withRSA\">uh5f61ql47lcwGLVly6eefviM5VLk1dyz7LGdZOxNSnVXHkAxX3e5wkJ6BRU66NWFZZxA+jKmu8/PqEPzWCa9g==</FRMA>\r\n"
				+ "</CAF>\r\n"
				+ "<TSTED>2022-07-15T12:32:56</TSTED>\r\n"
				+ "</DD>\r\n"
				+ "<FRMT algoritmo=\"SHA1withRSA\">TWh5ZzE5ck85QmJiRVVlVU5BL2l4bEVVZXcyWXVKNE8zb1JiSUQ5Z3dDakoxcVdxNXNWbTU4UHB0anNpd2FOb2RpNHZvYThrYVlIdzVkdHI2Znh3a1E9PQ==</FRMT>\r\n"
				+ "</TED>\r\n"
				+ "<TmstFirma>2022-07-15T12:32:56</TmstFirma>\r\n"
				+ "</Documento>\r\n"
				+ "<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"><SignedInfo><CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/><SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/><Reference URI=\"#B202207150032560000000003\"><Transforms><Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/></Transforms><DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><DigestValue>JsCua08QbGHZRABNEUSqp0SUmpA=</DigestValue></Reference></SignedInfo><SignatureValue>KGHlXrHyT6DCPDiFeFe8aiM7J92qDZGK/7183YwQosCQatcXQnU7zIyHXskkjtfxboyf3T1SVLsoCqYQtuTGO9b5aJD6htLsOZ7rAW+Kzna2wqEz3RcWS+QDXKJOcvxT4EJbnEjIr4Q4mG7KFjeDTjAl/RrN/6XgNdgbikWAweIoqxUkoXR0Ehv2QIFSj7DXxt7jDdrCyXIxoJ9ZE4MVb61p4K7CrMicQ+gMnEE5phIrLjEaHCV00JpVx8ir0qQtorIYNLASyPj3wzKbD3CZDvDHhC0mHuW8HAbh3Gzcp/XK2BwAQnVb9Ukh0raezLHu7O8BAiy0g4inR4/OOj8ucg==</SignatureValue><KeyInfo><KeyValue><RSAKeyValue><Modulus>ySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLkadQb8xX15Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRturqgW2zc4xJ02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7mkUVKUyf/dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SHcp/344bGhJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSw==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue><X509Data><X509Certificate>MIIH3TCCBcWgAwIBAgIKESP5LQABAAFMAjANBgkqhkiG9w0BAQsFADCBvzELMAkGA1UEBhMCQ0wxHTAbBgNVBAgTFFJlZ2lvbiBNZXRyb3BvbGl0YW5hMREwDwYDVQQHEwhTYW50aWFnbzEUMBIGA1UEChMLRS1DRVJUQ0hJTEUxIDAeBgNVBAsTF0F1dG9yaWRhZCBDZXJ0aWZpY2Fkb3JhMR4wHAYDVQQDExVFLUNFUlRDSElMRSBDQSBGRVMgMDIxJjAkBgkqhkiG9w0BCQEWF3NjbGllbnRlQGUtY2VydGNoaWxlLmNsMB4XDTIyMDUxMjE5MzUyMloXDTIzMDUxMjE5MzUyMlowgdkxCzAJBgNVBAYTAkNMMSIwIAYDVQQIExlNRVRST1BPTElUQU5BIERFIFNBTlRJQUdPMREwDwYDVQQHEwhTQU5USUFHTzE8MDoGA1UEChMzU0lTVEVNQVMgVEVDTk9MT0dJQ09TIElORk9STUFUSUNPUyBUUkFOU0ZPUk1BUFAgU1BBMQowCAYDVQQLDAEqMSEwHwYDVQQDExhDTEFVRElPIENPUlJFQSBCRVRBTkNPVVIxJjAkBgkqhkiG9w0BCQEWF0NDT1JSRUFAVFJBTlNGT1JNQVBQLkNMMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLkadQb8xX15Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRturqgW2zc4xJ02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7mkUVKUyf/dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SHcp/344bGhJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSwIDAQABo4ICvTCCArkwggFfBgNVHSAEggFWMIIBUjCCAU4GCCsGAQQBw1IFMIIBQDA9BggrBgEFBQcCARYxaHR0cHM6Ly93d3cuZS1jZXJ0Y2hpbGUuY2wvcG9saXRpY2FzLXktcHJhY3RpY2FzLzCB/gYIKwYBBQUHAgIwgfEege4ARQBsACAAcgBlAHMAcABvAG4AZABlAHIAIABlAHMAdABlACAAZgBvAHIAbQB1AGwAYQByAGkAbwAgAGUAcwAgAHUAbgAgAHIAZQBxAHUAaQBzAGkAdABvACAAaQBuAGQAaQBzAHAAZQBuAHMAYQBiAGwAZQAgAHAAYQByAGEAIABkAGEAcgAgAGkAbgBpAGMAaQBvACAAYQBsACAAcAByAG8AYwBlAHMAbwAgAGQAZQAgAGMAZQByAHQAaQBmAGkAYwBhAGMAaQDzAG4ALgAgAFAAbwBzAHQAZQByAGkAbwByAG0AZQBuAHQAZQAsMB0GA1UdDgQWBBSAYI7nYNtsjzfZ5hi49+IB28bYzTALBgNVHQ8EBAMCBPAwIwYDVR0RBBwwGqAYBggrBgEEAcEBAaAMFgoxNDMzNjk2MC05MB8GA1UdIwQYMBaAFHTWIbP0WugtfLtZBmND72m0OpMEMEAGA1UdHwQ5MDcwNaAzoDGGL2h0dHA6Ly9jcmwuZWNlcnRjaGlsZS5jbC9FLUNFUlRDSElMRUNBRkVTMDIuY3JsMD0GCCsGAQUFBwEBBDEwLzAtBggrBgEFBQcwAYYhaHR0cDovL29jc3BmZXMuZWNlcnRjaGlsZS5jbC9vY3NwMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIHd0k2X1DqGiZ0Gh4jOb4OvzGBFhaS+OIKen20CAWQCAQIwIwYDVR0SBBwwGqAYBggrBgEEAcEBAqAMFgo5NjkyODE4MC01MA0GCSqGSIb3DQEBCwUAA4ICAQA1N0v7yylmdqxUQK6SYJ3KUrP+0p5vq2iOkoQDa4cf6i8/RI1x31XoyuVSCT9G5GTI9O/N6sf6a2ClFdvpHsDP+vPEkVmoHB9Uiie4zxptC7xuWC1Gs2HIkSbQERr5oHVYGDjXn/n5HdwNoDkTxzXmE2Xd5sr+fk4stHckHileCUYSYuCUOPHXjMa6WArFZ/dUYqgspWVSbZzOrGxTkTfCXasacl7xrCxoF//zF+twiv6WLItV4mR7hULUMEU7dk7xEAn8xtQtYqkb8PMrRfzeQZT3Zc8J2wENi+GA5PtDtGJbq6BYNQpIB4Oqql+n3sCdFYPO3L+0uSIRaMCB+T8jgCeKDzEv+FOTxIs02BsYDBxjkjk1r4h71ZKKxHUSiX+qsJYiYWZF4NYpucPAUCxpUcZUhfYjxfzRoxl70ubBATn6apsuAh/gOjTkod54k99frNdJoS0HSoQHua/JEKxbGQCY3tNMMcWHGOA1gI8OLI6dEwfdHNdN5PSCQnAvsnQ9kdcj2fLc070cxWy32Nr4aMQZqNONGZEQnz3CBWJwEaMDqJHd/7Ka7RLM4RjFqP76MMJIRwK+4iXHtjr54k5i8m4oLPO1ZuOuZN+VDB7+xx3eshLbRQS2kJxaeYCX8sG7WKcvl1Nc10gZSC1xp6jBYer6VC7Q7tc3qfDUhHC7pg==</X509Certificate></X509Data></KeyInfo></Signature></DTE>\r\n"
				+ "</SetDTE>\r\n"
				+ "<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"><SignedInfo><CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/><SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/><Reference URI=\"#S20220715003300\"><Transforms><Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/></Transforms><DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><DigestValue>HQ8CenqcQPn+hwAAXLibZ1Qjhcg=</DigestValue></Reference></SignedInfo><SignatureValue>Sssg5fFtoYYmbuGTIH7PRY6ed1QjcYkF/V52qUXwuAmdKslneNDEy/dNC4Y1W3Q1UX1rGq7Zm4fajqW8GlOSxyfMo4Q8CR5pBGh58l0smTGeNLxwpFRzXwGbTCeQy9QNsI1ORNmuLsRc7x++3mxYeF48M/tKTotDAXIV5F2tWhcruyNhiKvxJ0J2nwEu3N4qbJILZ96mDfbCNfbl1r0CoGa7MbG925i39fNCf2rZq4Tjajs7uGz2/K7UcEcAU+aKIV10HqqDEkfOdN5Akb4rc7Hkk528seyk+8mwNyopfjCIofFzuxhGLPtNSjbwiG74Zvz9R+mS8n8p3OCPAEb78w==</SignatureValue><KeyInfo><KeyValue><RSAKeyValue><Modulus>ySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLkadQb8xX15Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRturqgW2zc4xJ02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7mkUVKUyf/dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SHcp/344bGhJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSw==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue><X509Data><X509Certificate>MIIH3TCCBcWgAwIBAgIKESP5LQABAAFMAjANBgkqhkiG9w0BAQsFADCBvzELMAkGA1UEBhMCQ0wxHTAbBgNVBAgTFFJlZ2lvbiBNZXRyb3BvbGl0YW5hMREwDwYDVQQHEwhTYW50aWFnbzEUMBIGA1UEChMLRS1DRVJUQ0hJTEUxIDAeBgNVBAsTF0F1dG9yaWRhZCBDZXJ0aWZpY2Fkb3JhMR4wHAYDVQQDExVFLUNFUlRDSElMRSBDQSBGRVMgMDIxJjAkBgkqhkiG9w0BCQEWF3NjbGllbnRlQGUtY2VydGNoaWxlLmNsMB4XDTIyMDUxMjE5MzUyMloXDTIzMDUxMjE5MzUyMlowgdkxCzAJBgNVBAYTAkNMMSIwIAYDVQQIExlNRVRST1BPTElUQU5BIERFIFNBTlRJQUdPMREwDwYDVQQHEwhTQU5USUFHTzE8MDoGA1UEChMzU0lTVEVNQVMgVEVDTk9MT0dJQ09TIElORk9STUFUSUNPUyBUUkFOU0ZPUk1BUFAgU1BBMQowCAYDVQQLDAEqMSEwHwYDVQQDExhDTEFVRElPIENPUlJFQSBCRVRBTkNPVVIxJjAkBgkqhkiG9w0BCQEWF0NDT1JSRUFAVFJBTlNGT1JNQVBQLkNMMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAySS6FARwZZQ2P8zO+xwoB70bSKEQogcMIEMhmBTMoNbKXvkJ7haHtAciTMdKBPoDhLkadQb8xX15Th5DGH3iYWexBrAIKHzlBhj/W2XUYOQT9L+7Byo09ZVdNgrGNbdhdnkQ/O87uUdFRturqgW2zc4xJ02863lnFg+1350pLQDJfdEvtNblNMslie+KSBE+OwSspvTcVAy7to0heu376qPixH7mkUVKUyf/dLRnJ1QUP3fbfF5Q5FXvR1rQLsQeOPVmT7VVoykk/RQOSiKEMumag+YwSAEaUT/pB+SHcp/344bGhJqip4g8GaPkR2baNMc2BVrAhowdTxuR5GxiSwIDAQABo4ICvTCCArkwggFfBgNVHSAEggFWMIIBUjCCAU4GCCsGAQQBw1IFMIIBQDA9BggrBgEFBQcCARYxaHR0cHM6Ly93d3cuZS1jZXJ0Y2hpbGUuY2wvcG9saXRpY2FzLXktcHJhY3RpY2FzLzCB/gYIKwYBBQUHAgIwgfEege4ARQBsACAAcgBlAHMAcABvAG4AZABlAHIAIABlAHMAdABlACAAZgBvAHIAbQB1AGwAYQByAGkAbwAgAGUAcwAgAHUAbgAgAHIAZQBxAHUAaQBzAGkAdABvACAAaQBuAGQAaQBzAHAAZQBuAHMAYQBiAGwAZQAgAHAAYQByAGEAIABkAGEAcgAgAGkAbgBpAGMAaQBvACAAYQBsACAAcAByAG8AYwBlAHMAbwAgAGQAZQAgAGMAZQByAHQAaQBmAGkAYwBhAGMAaQDzAG4ALgAgAFAAbwBzAHQAZQByAGkAbwByAG0AZQBuAHQAZQAsMB0GA1UdDgQWBBSAYI7nYNtsjzfZ5hi49+IB28bYzTALBgNVHQ8EBAMCBPAwIwYDVR0RBBwwGqAYBggrBgEEAcEBAaAMFgoxNDMzNjk2MC05MB8GA1UdIwQYMBaAFHTWIbP0WugtfLtZBmND72m0OpMEMEAGA1UdHwQ5MDcwNaAzoDGGL2h0dHA6Ly9jcmwuZWNlcnRjaGlsZS5jbC9FLUNFUlRDSElMRUNBRkVTMDIuY3JsMD0GCCsGAQUFBwEBBDEwLzAtBggrBgEFBQcwAYYhaHR0cDovL29jc3BmZXMuZWNlcnRjaGlsZS5jbC9vY3NwMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIHd0k2X1DqGiZ0Gh4jOb4OvzGBFhaS+OIKen20CAWQCAQIwIwYDVR0SBBwwGqAYBggrBgEEAcEBAqAMFgo5NjkyODE4MC01MA0GCSqGSIb3DQEBCwUAA4ICAQA1N0v7yylmdqxUQK6SYJ3KUrP+0p5vq2iOkoQDa4cf6i8/RI1x31XoyuVSCT9G5GTI9O/N6sf6a2ClFdvpHsDP+vPEkVmoHB9Uiie4zxptC7xuWC1Gs2HIkSbQERr5oHVYGDjXn/n5HdwNoDkTxzXmE2Xd5sr+fk4stHckHileCUYSYuCUOPHXjMa6WArFZ/dUYqgspWVSbZzOrGxTkTfCXasacl7xrCxoF//zF+twiv6WLItV4mR7hULUMEU7dk7xEAn8xtQtYqkb8PMrRfzeQZT3Zc8J2wENi+GA5PtDtGJbq6BYNQpIB4Oqql+n3sCdFYPO3L+0uSIRaMCB+T8jgCeKDzEv+FOTxIs02BsYDBxjkjk1r4h71ZKKxHUSiX+qsJYiYWZF4NYpucPAUCxpUcZUhfYjxfzRoxl70ubBATn6apsuAh/gOjTkod54k99frNdJoS0HSoQHua/JEKxbGQCY3tNMMcWHGOA1gI8OLI6dEwfdHNdN5PSCQnAvsnQ9kdcj2fLc070cxWy32Nr4aMQZqNONGZEQnz3CBWJwEaMDqJHd/7Ka7RLM4RjFqP76MMJIRwK+4iXHtjr54k5i8m4oLPO1ZuOuZN+VDB7+xx3eshLbRQS2kJxaeYCX8sG7WKcvl1Nc10gZSC1xp6jBYer6VC7Q7tc3qfDUhHC7pg==</X509Certificate></X509Data></KeyInfo></Signature></EnvioBOLETA>";
		
		XmlSigner signerUtils = new XmlSigner();
		if( xmlcontentSetDTE != null && !xmlcontentSetDTE.trim().isBlank()) {
			boolean resultSetDTE = signerUtils.validateSignature(xmlcontentSetDTE, "SetDTE", "Documento");
			System.out.println("La firma del xml SetDTE: " + (resultSetDTE?"Es Valida":"No es valida") );			
		}

		if( xmlcontentDTE != null && !xmlcontentDTE.trim().isBlank()) {
			boolean resultDTE = signerUtils.validateSignature(xmlcontentDTE, "Documento", null);
			System.out.println("La firma del xml DTE: " + (resultDTE?"Es Valida":"No es valida") );			
		}
	}

}
